module Image
  module Organizer
    BASE_COLOR: String
    FAIL_COLOR: String
    PASS_COLOR: String
    WARN_COLOR: String
    VERSION: String

    class CLI
      def self.exit_on_failure?: -> bool

      def self.start: -> untyped

      def help: -> untyped

      def pretend: -> untyped

      def process: -> untyped

      def tree: -> untyped

      def version: -> untyped
    end

    self.@matched_id_lines: untyped

    def self.extract_sequences: (array[String] lines) -> untyped

    def self.extract_volumes: (array[String] id_lines) -> untyped

    def self.fetch_info: (String line) -> String

    def self.filter_lines: (array[String] lines) -> untyped

    def self.pretend: -> untyped

    def self.process: -> untyped

    def self.setup: -> untyped

    def self.version: -> untyped

    private

    def self.session_layout?: (bool _dry_run) -> bool

    def self.session_ingest?: (bool _dry_run) -> bool

    def self.session_status?: (bool _dry_run) -> bool
  end
end
